apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 922648155914.dkr.ecr.us-east-2.amazonaws.com/simplebank:8cdf77dd73bfbc736962a908016df5aa8a23ec7c
        ports:
        - containerPort: 8080